// The anti-hand-edit gate, and the file the header of js/data/lots.js promises exists.
//
// Every line of the shipped pool is re-read off disk as text, JSON-parsed, and re-measured
// with js/core/solve.js and js/core/jug.js alone. The numbers printed next to it in the file
// have to come out again: `par`, `solutions`, `states`, and the route — which is replayed
// through the model move by move, so a baked route that a player could not actually perform
// fails here even if its length is right.
//
// Nothing in this file imports js/core/make.js: the point is to check the artefact against the
// search, not against the sampler that produced it.

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { test, run, ok, eq } from '../tools/harness.mjs';
import { solve, census } from '../js/core/solve.js';
import {
  compile, validate, toSpec, encode, decode, apply, effective, isGoal, stateSpace, SPACE_LIMIT,
  FILL, DUMP, POUR,
} from '../js/core/jug.js';
import { canMeasureAny, gcdAll } from '../js/core/theorem.js';
import { LOTS, TIERS_META } from '../js/data/lots.js';
import { byId, lotsIn, campaign, levelAt, randomLot, dailyLot, stats, tierByKey } from '../js/core/library.js';
import { hashSeed } from '../js/core/rng.js';

const here = dirname(fileURLToPath(import.meta.url));
const dataPath = join(here, '..', 'js', 'data', 'lots.js');

// Read the artefact the way a hand-edit would leave it: as text. Importing the module is the
// convenience version; the assertions below run on what is actually on disk.
const text = readFileSync(dataPath, 'utf8');
const rows = text.split('\n')
  .filter((line) => /^\s*\{"id":/.test(line))
  .map((line) => JSON.parse(line.trim().replace(/,$/, '')));
const metaLine = text.split('\n').find((line) => line.startsWith('export const TIERS_META'));
const meta = JSON.parse(metaLine.replace('export const TIERS_META = ', '').replace(/;$/, ''));

// The route as baked is {op,i,j}; the search's is the same triple plus the `id` it indexes
// into the compiled action list. Compare the meaning, not the bookkeeping.
const meaning = (a) => `${a.op}:${a.i}${a.j === undefined ? '' : a.j}`;

function replay(row) {
  const comp = compile(row.spec);
  let pos = Uint16Array.from(comp.start);
  for (let n = 0; n < row.route.length; n++) {
    const raw = row.route[n];
    const act = comp.acts.find((a) => meaning(a) === meaning(raw));
    if (!act) return { err: `step ${n} is not an action this bench has` };
    if (!effective(comp, pos, act)) return { err: `step ${n} (${meaning(act)}) changes nothing at ${Array.from(pos)}` };
    pos = apply(comp, pos, act);
  }
  if (!isGoal(comp, pos)) return { err: `the route ends at ${Array.from(pos)}, which is not ${comp.need} in a target bucket` };
  return { comp, pos: Array.from(pos) };
}

test('the pool is on disk, parses, and is the pool the game imports', () => {
  ok(text.includes('// Generated by tools/bake.mjs'), 'the header says where it came from');
  ok(rows.length >= 60, `${rows.length} lines parsed out of the file text`);
  eq(rows.length, LOTS.length, 'the imported module and the bytes on disk are the same pool');
  eq(rows.map((r) => r.id), LOTS.map((r) => r.id), 'in the same order, so the campaign is reproducible');
  eq(new Set(rows.map((r) => r.id)).size, rows.length, 'ids are unique');
  eq(text.split('\n').filter((l) => /^\s*\{"id":/.test(l)).length, rows.length, 'one puzzle per line, which is what makes a hand-edit visible');
  for (const r of rows) {
    if (!new RegExp(`^${r.tier}-\\d\\d$`).test(r.id)) return ok(false, `id ${r.id} does not match its band ${r.tier}`);
  }
  ok(true, 'every id is its band plus a two-digit number');
});

test('every printed line reproduces its own numbers when re-solved from the serialised spec', () => {
  const bad = [];
  let maxSpace = 0;
  let maxStates = 0;
  for (const row of rows) {
    const id = row.id;
    const err = validate(row.spec);
    if (err) { bad.push(`${id}: ${err}`); continue; }
    const space = stateSpace(row.spec.caps);
    maxSpace = Math.max(maxSpace, space);
    if (space > SPACE_LIMIT) bad.push(`${id}: ${space} codes over the ${SPACE_LIMIT} ceiling`);
    const again = solve(row.spec, { limit: 400000 });
    if (!again.ok) bad.push(`${id}: the shipped puzzle does not solve`);
    else {
      if (again.par !== row.par) bad.push(`${id}: printed par ${row.par}, search says ${again.par}`);
      if (again.solutions !== row.solutions) bad.push(`${id}: printed ${row.solutions} solutions, search says ${again.solutions}`);
      if (again.path.length !== row.par) bad.push(`${id}: route is ${again.path.length} long, par is ${row.par}`);
      if (again.ok && again.par !== row.route.length) bad.push(`${id}: baked route has ${row.route.length} steps, par is ${row.par}`);
      if (JSON.stringify(again.path.map(meaning)) !== JSON.stringify(row.route.map(meaning))) {
        bad.push(`${id}: the baked route is not the route the search returns`);
      }
    }
    const c = census(row.spec, 400000);
    if (c.truncated) bad.push(`${id}: census truncated at ${c.states}`);
    if (c.states !== row.states) bad.push(`${id}: printed ${row.states} states, census says ${c.states}`);
    maxStates = Math.max(maxStates, c.states);
    const r = replay(row);
    if (r.err) bad.push(`${id}: ${r.err}`);
    // The theorem is the independent screen: nothing shipped may contradict it.
    if (!canMeasureAny(row.spec.caps, row.spec.need)) bad.push(`${id}: gcd says ${row.spec.need} is unmeasurable in ${row.spec.caps}`);
    // The spec must survive the round trip through its own serialised face.
    if (JSON.stringify(toSpec(compile(row.spec))) !== JSON.stringify(row.spec)) {
      bad.push(`${id}: toSpec(compile(spec)) !== spec, so the file is not in canonical form`);
    }
    // Encoding has to be dense enough for the search to index states by number.
    const comp = compile(row.spec);
    if (encode(comp, decode(comp, space - 1)) !== space - 1) bad.push(`${id}: the mixed-radix code does not cover its own space`);
  }
  eq(bad, [], 'every line of the pool re-measures to what it prints');
  eq(rows.length >= 60, true, `${rows.length} puzzles checked, each against par, solutions, states, route and theorem`);
  ok(maxSpace <= SPACE_LIMIT, `the largest code space shipped is ${maxSpace}, inside the ${SPACE_LIMIT} gate`);
  ok(maxStates <= maxSpace, `and the largest reachable set is ${maxStates}`);
});

test('the band metadata is measured off the pool, not typed in', () => {
  const bad = [];
  for (const t of meta) {
    const pars = rows.filter((r) => r.tier === t.key).map((r) => r.par).sort((a, b) => a - b);
    if (!pars.length) { bad.push(`${t.key}: no puzzles`); continue; }
    if (pars[0] !== t.min || pars[pars.length - 1] !== t.max) bad.push(`${t.key}: meta says ${t.min}-${t.max}, the pool says ${pars[0]}-${pars[pars.length - 1]}`);
    const buckets = [...new Set(rows.filter((r) => r.tier === t.key).map((r) => r.spec.caps.length))].sort((a, b) => a - b);
    const bTxt = buckets.length === 1 ? `${buckets[0]} 只桶` : `${buckets[0]}-${buckets[buckets.length - 1]} 只桶`;
    const pTxt = t.min === t.max ? `${t.min} 次` : `${t.min}-${t.max} 次`;
    if (!t.blurb.includes(bTxt)) bad.push(`${t.key}: blurb "${t.blurb}" disagrees with ${bTxt}`);
    if (!t.blurb.includes(pTxt)) bad.push(`${t.key}: blurb "${t.blurb}" disagrees with ${pTxt}`);
    if (new Set(pars).size < 2) bad.push(`${t.key}: every puzzle has par ${pars[0]}, which is one puzzle in ${pars.length} costumes`);
  }
  eq(bad, [], 'TIERS_META is the pool measured, and each band ships a curve rather than a constant');
  eq(meta.map((m) => m.key), ['drip', 'measure', 'blend', 'decant'], 'four bands, in the order the game plays them');
  for (let i = 1; i < meta.length; i++) {
    ok(meta[i].min > meta[i - 1].max, `${meta[i].key} starts above where ${meta[i - 1].key} ends`);
  }
  eq(TIERS_META, meta, 'and the imported metadata is the file metadata');
  const counts = meta.map((m) => rows.filter((r) => r.tier === m.key).length);
  ok(counts.every((n) => n >= 10), `each band carries ${counts.join('/')} puzzles`);
});

test('library.js is a lookup over that file and nothing more', () => {
  eq(campaign().length, rows.length, 'the campaign is the whole pool, in the baked order');
  let lastPar = -Infinity;
  const tierSeen = [];
  for (const lot of campaign()) {
    if (lot.tier !== tierSeen[tierSeen.length - 1]) tierSeen.push(lot.tier);
    if (lot.par < lastPar) { ok(false, `level ${lot.id} drops below the previous band's ordering`); break; }
    lastPar = lot.par;
  }
  eq(tierSeen, meta.map((m) => m.key), 'bands appear once each, in order');
  eq(byId(rows[0].id).par, rows[0].par, 'byId finds the first line');
  eq(byId('not-a-lot'), null, 'and says so when there is nothing to find');
  eq(lotsIn('decant').length, rows.filter((r) => r.tier === 'decant').length);
  eq(levelAt(0).id, rows[0].id, 'levelAt is zero-based');
  eq(levelAt(-1).id, rows[rows.length - 1].id, 'and wraps backwards rather than falling off the end');
  eq(levelAt(rows.length).id, rows[0].id, 'as it wraps forwards');
  eq(tierByKey('decant').key, 'decant');
  eq(tierByKey('nonsense').key, 'drip', 'an unknown band falls back to the easiest one');
  const s = stats();
  eq(s.lots, rows.length, 'the harness stats count the same pool');
  for (const t of meta) {
    const st = s.byTier[t.key];
    ok(st && st.n > 0, `${t.key} reports a tally`);
    eq([st.min, st.max], [t.min, t.max], `${t.key} stats agree with its metadata`);
    ok(st.parMed >= st.min && st.parMed <= st.max, `${t.key} median sits inside its band (${st.parMed})`);
  }
});

test('the daily and the shared random link are a function of their seed, on any device', () => {
  // hashSeed is FNV-1a run over the two bytes of each UTF-16 code unit, low byte first. That
  // is a *specification*, and it is recomputed here with BigInt instead of Math.imul, so a
  // broken 32-bit multiply in core cannot agree with itself.
  const PRIME = 0x01000193n;
  const MASK = 0xffffffffn;
  function fnv1aUtf16le(str) {
    let h = 0x811c9dc5n;
    for (let i = 0; i < str.length; i++) {
      const c = str.charCodeAt(i);
      for (const byte of [c & 0xff, (c >> 8) & 0xff]) {
        h ^= BigInt(byte);
        h = (h * PRIME) & MASK;
      }
    }
    return Number(h);
  }
  eq(hashSeed(''), 0x811c9dc5, 'the empty string is the FNV offset basis, unchanged');
  for (const key of ['daily|2026-01-01', 'daily|2026-09-27', 'random|blend|4kq2', 'random|drip|zzzzzz', 'a', 'ab', '倒水']) {
    eq(hashSeed(key), fnv1aUtf16le(key), `the shipped hash re-derives as FNV-1a over UTF-16LE for ${key}`);
    ok(hashSeed(key) >= 0 && hashSeed(key) <= 0xffffffff, `${key} hashes into the unsigned 32-bit range`);
  }
  const pickIn = (list, salt, seed) => list[hashSeed(`${salt}|${seed}`) % list.length].id;
  eq(pickIn(rows, 'daily', '2026-09-27'), dailyLot('2026-09-27').id, 'the library picks from the whole pool, in file order');
  const day = '2026-09-27';
  eq(dailyLot(day).id, pickIn(rows, 'daily', day), 'the daily puzzle is the pool index the date hashes to');
  eq(dailyLot(day).id, dailyLot(day).id, 'twice in a row, of course');
  const blendRows = rows.filter((r) => r.tier === 'blend');
  eq(randomLot('4kq2', 'blend').id, pickIn(blendRows, 'random', '4kq2'), 'and a #/random/blend/4kq2 link indexes inside its own band');
  eq(randomLot('4kq2', 'blend').tier, 'blend', 'which stays inside the band it names');
  for (const tier of meta.map((m) => m.key)) {
    eq(randomLot('fixedseed', tier).tier, tier, `#/random/${tier}/fixedseed stays in ${tier}`);
  }
  const ids = new Set();
  for (let i = 0; i < 40; i++) ids.add(dailyLot(`2026-01-${String(i + 1).padStart(2, '0')}`).id);
  ok(ids.size > 12, `40 consecutive days draw ${ids.size} distinct puzzles, so the date is doing real work`);
  const byTier = {};
  for (const r of rows) byTier[r.tier] = (byTier[r.tier] || 0) + 1;
  eq(Object.keys(byTier).length, 4, 'four bands to route into');
});

test('a route replayed one step at a time is the puzzle a player can actually finish', () => {
  // The panel's hint walks this same route, so the prefix has to stay off the goal: if step
  // n-1 of a par-n route already measured the number, par would be wrong by one.
  const bad = [];
  for (const row of rows) {
    const comp = compile(row.spec);
    let pos = Uint16Array.from(comp.start);
    for (let n = 0; n < row.route.length - 1; n++) {
      const act = comp.acts.find((a) => meaning(a) === meaning(row.route[n]));
      pos = apply(comp, pos, act);
      if (isGoal(comp, pos)) bad.push(`${row.id}: goal already reached after ${n + 1} of ${row.par} steps`);
    }
    const last = row.route[row.route.length - 1];
    pos = apply(comp, pos, comp.acts.find((a) => meaning(a) === meaning(last)));
    if (!isGoal(comp, pos)) bad.push(`${row.id}: the last step does not land on the goal`);
    const target = Array.isArray(row.spec.target) ? row.spec.target : [row.spec.target];
    if (!target.some((t) => pos[t] === row.spec.need)) bad.push(`${row.id}: final state has no target bucket on ${row.spec.need}`);
  }
  eq(bad, [], `${rows.length} baked routes each reach the goal on exactly their par-th step`);
  const sample = replay(rows.find((r) => r.spec.caps.length === 2));
  ok(!sample.err, `a two-bucket route replays clean: ${JSON.stringify(sample.pos)}`);
  ok(rows.some((r) => r.spec.caps.length === 3), 'the pool ships three-bucket puzzles');
  ok(rows.some((r) => r.spec.caps.length === 4), 'and four-bucket ones, so the mixed-radix code is used for k = 4 too');
  eq(rows.every((r) => r.spec.start.every((v) => v === 0)), true, 'every shipped puzzle starts empty, which is what makes par a distance from zero');
});

test('the shipped numbers are impossible to grade by eye, which is the point', () => {
  // A handful of hand-checkable facts about the pool, so that "the file was regenerated" is
  // not the only thing this suite can say. These are read off the file, then re-derived.
  const two = rows.filter((r) => r.spec.caps.length === 2);
  ok(two.length > 0, `${two.length} two-bucket puzzles`);
  let badParity = 0;
  for (const r of two) {
    // With two buckets and an empty start, every amount on the bench is a multiple of
    // gcd(a,b): the invariant the theorem is built from, checked state by state on the route.
    const g = gcdAll(r.spec.caps);
    if (r.spec.need % g !== 0) badParity++;
    const comp = compile(r.spec);
    let pos = Uint16Array.from(comp.start);
    for (const raw of r.route) {
      const act = comp.acts.find((a) => meaning(a) === meaning(raw));
      pos = apply(comp, pos, act, new Uint16Array(comp.k));
      for (let i = 0; i < comp.k; i++) if (pos[i] % g !== 0) badParity++;
    }
  }
  eq(badParity, 0, 'nothing on any two-bucket route ever leaves the gcd class it started in');
  const hardest = rows.reduce((a, b) => (b.par > a.par ? b : a));
  eq(hardest.par, Math.max(...rows.map((r) => r.par)), 'the hardest printed puzzle is the maximum printed par');
  ok(hardest.par >= 12, `${hardest.id} asks for ${hardest.par} moves, which is past what a person can enumerate on their fingers`);
  ok(rows.every((r) => r.solutions >= 1), 'every puzzle has at least one optimal route — it solved');
  const multi = rows.filter((r) => r.solutions > 1);
  ok(multi.length > rows.length / 2, `${multi.length} of ${rows.length} puzzles have more than one shortest answer, so 解法 is a real number`);
  eq([FILL, DUMP, POUR], ['fill', 'dump', 'pour'], 'and the routes are written in exactly those three operations');
});

run();
